# Generated by Django 2.0.7 on 2018-07-27 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品价格')),
                ('desc', models.CharField(max_length=1000, verbose_name='描述')),
                ('picture', models.ImageField(default='normal.png', upload_to='static/images/goods', verbose_name='商品照片')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='名称')),
                ('desc', models.CharField(default='商品描述', max_length=200, verbose_name='描述')),
                ('flag', models.IntegerField(default=0)),
                ('picture', models.ImageField(default='normal.png', upload_to='static/image/good_type')),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'goods_Type',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberapp.GoodsType'),
        ),
    ]
