# Generated by Django 2.0.7 on 2018-07-27 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(db_column='aname', max_length=30, verbose_name='姓名')),
                ('address', models.CharField(db_column='address', max_length=150, verbose_name='收站点')),
                ('cellphone', models.CharField(db_column='cellphone', max_length=15, verbose_name='手机号')),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_column='uemail', max_length=40, verbose_name='邮箱')),
                ('uname', models.CharField(db_column='uname', max_length=50, verbose_name='用户名')),
                ('upassword', models.CharField(db_column='upassword', max_length=200, verbose_name='密码')),
                ('isban', models.BooleanField(default=False, verbose_name='禁用')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo'),
        ),
    ]
